PREFIX search: <http://www.openrdf.org/contrib/lucenesail#>
PREFIX lod: <https://linkedopendata.eu/entity/>
PREFIX mdcs: <http://the-qa-company.com/modelcustom/>

SELECT (count(*) as ?c) {
	?subj search:matches [
	      search:query "IBM" ;
		  search:indexid mdcs:Common
	] .
	?subj lodd:P35 lod:Q9934 # Project
}
